config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts do
  	member do
  		get "like", to: "posts#upvote"
  		get "dislike", to: "posts#downvote"
  	end
  	resources :comments
  end

  root 'posts#index'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
	acts_as_votable
	belongs_to :user
	has_many :comments
	has_attached_file :image, styles: { medium: "700x500#", small: "350x250>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
  	devise_parameter_sanitizer.for(:sign_up) << :name
  	devise_parameter_sanitizer.for(:account_update) << :name
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!
	
	def create
		@post = Post.find(params[:post_id])
		@comment = Comment.create(params[:comment].permit(:content))
		@comment.user_id = current_user.id
		@comment.post_id = @post.id

		if @comment.save
			redirect_to post_path(@post)
		else
			render 'new'
		end
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :find_post, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
	before_action :authenticate_user!, except: [:index, :show]

	def index
		@posts = Post.all.order("created_at DESC")
	end

	def show
		@comments = Comment.where(post_id: @post)
		@random_post = Post.where.not(id: @post).order("RANDOM()").first
	end

	def new
		@post = current_user.posts.build
	end

	def create
		@post = current_user.posts.build(post_params)

		if @post.save
			redirect_to @post
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @post.update(post_params)
			redirect_to @post
		else
			render 'edit'
		end
	end

	def destroy
		@post.destroy
		redirect_to root_path
	end

	def upvote
		@post.upvote_by current_user
		redirect_to :back
	end

	def downvote
		@post.downvote_by current_user
		redirect_to :back
	end

	private

	def find_post
		@post = Post.find(params[:id])
	end

	def post_params
		params.require(:post).permit(:title, :link, :description, :image)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_form.html.erb
<%= form_for ([@post, @post.comments.build]) do |f| %>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit :submit, class: "button" %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Muse</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <link href="http://cdnjs.cloudflare.com/ajax/libs/normalize/3.0.1/normalize.min.css" rel="stylesheet"></link>
  <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet"></link>
</head>
<body>
	<header>
			<div class="wrapper clearfix">
				<div id="logo">
					<%= link_to "Muse", root_path %>
				</div>
				<nav>
					<% if user_signed_in? %>
	          <%= link_to current_user.name, edit_user_registration_path %>
	          <%= link_to "Add New Inspiration", new_post_path, class: "button" %>
	        <% else %>
	          <%= link_to "Sign in", new_user_session_path %>
	          <%= link_to "Sign Up", new_user_registration_path, class: "button" %>
	        <% end %>
				</nav>
			</div>
		</header>
	<p class="notice">
		<%= notice %>
	</p>
	<p class="alert">
		<%= alert %>
	</p>
	<div class="wrapper">
		<%= yield %>
	</div>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :link %><br>
    <%= f.text_field :link %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Inspiration</h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<% if user_signed_in? %>
  <p id="intro">
    Hello
    <%= current_user.name %>
    <br/>
    <span>
      Share your inspiration and see what's inspiring others.
    </span>
  </p>
<% else %>
  <p id="intro">
    What's your muse?
    <br/>
    <span>
      Share your inspiration and see what's inspiring others.
    </span>
  </p>
<% end %>
<div id="posts">
  <% @posts.each do |post| %>
    <div class="post">
      <div class="post_image">
        <%= link_to (image_tag post.image.url(:small)), post %>
      </div>
      <div class="post_content">
        <div class="title">
          <h2>
            <%= link_to post.title, post %>
          </h2>
        </div>
        <div class="data clearfix">
          <p class="username">
            Shared by
            <%= post.user.name %>
          </p>
          <p class="buttons">
            <span>
              <i class="fa fa-comments-o"></i>
              <%= post.comments.count %>
            </span>
            <span>
              <i class="fa fa-thumbs-o-up"></i>
              <%= post.get_likes.size %>
            </span>
          </p>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<h1>Add New Inspiration</h1>

<%= render 'form' %>

app/views/posts/show.html.erb
<div id="post_show">
  <h1>
    <%= @post.title %>
  </h1>
  <p class="username">
    Shared by
    <%= @post.user.name %>
    about
    <%= time_ago_in_words(@post.created_at) %>
  </p>
  <div class="clearfix">
    <div class="post_image_description">
      <%= image_tag @post.image.url(:medium) %>
      <div class="description">
        <%= simple_format(@post.description) %>
      </div>
    </div>
    <div class="post_data">
      <%= link_to "Visit Link", @post.link, class: "button" %>
      <%= link_to like_post_path(@post), method: :get, class: "data" do %>
        <i class="fa fa-thumbs-o-up"></i>
        <%= pluralize(@post.get_upvotes.size, "Like") %>
      <% end %>
      <%= link_to dislike_post_path(@post), method: :get, class: "data" do %>
        <i class="fa fa-thumbs-o-down"></i>
        <%= pluralize(@post.get_downvotes.size, "Dislike") %>
      <% end %>
      <p class="data">
        <i class="fa fa-comments-o"></i>
        <%= pluralize(@post.comments.count, "Comment") %>
      </p>
      <% if @post.user == current_user %>
        <%= link_to "Edit", edit_post_path(@post), class: "data" %>
        <%= link_to "Delete", post_path(@post), method: :delete, data: { confirm: "Are you sure?" }, class: "data" %>
      <% end %>
    </div>
    <div id="random_post">
      <h3>Random Inspiration</h3>
      <div class="post">
        <div class="post_image">
          <%= link_to (image_tag @random_post.image.url(:medium)), post_path(@random_post) %>
        </div>
        <div class="post_content">
          <div class="title">
            <h2>
              <%= link_to @random_post.title, post_path(@random_post) %>
            </h2>
          </div>
          <div class="data clearfix">
            <p class="username">
              Shared by
              <%= @random_post.user.name %>
            </p>
            <p class="buttons">
              <span>
                <i class="fa fa-comments-o"></i>
                <%= @random_post.comments.count %>
              </span>
              <span>
                <i class="fa fa-thumbs-o-up"></i>
                <%= @random_post.get_likes.size %>
              </span>
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div id="comments">
  <h2 class="comment_count">
    <%= pluralize(@post.comments.count, "Comment") %>
  </h2>
  <% @comments.each do |comment| %>
    <div class="comment">
      <p class="username">
        <%= comment.user.name %>
      </p>
      <p class="content">
        <%= comment.content %>
      </p>
    </div>
  <% end %>
  <%= render "comments/form" %>
</div>